"""initial

Revision ID: 97c3b9fbf8a3
Revises:
Create Date: 2025-12-08 16:41:34.254803

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "97c3b9fbf8a3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
