services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shop-scout-api
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/src:/scout_backend/src
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - DEBUG=true
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000/" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - shop-scout-network

  # Frontend service - Dockerfile will be provided by frontend team


networks:
  shop-scout-network:
    driver: bridge
